// Generated by `wit-bindgen` 0.45.1. DO NOT EDIT!
// Options used:
#[derive(Clone)]
pub struct PrivateCloud {
  pub management_cluster: _rt::String,
  pub internet: Option<_rt::String>,
  pub identity_sources: Option<_rt::Vec::<_rt::String>>,
  pub availability: Option<_rt::String>,
  pub encryption: Option<_rt::String>,
  pub extended_network_blocks: Option<_rt::Vec::<_rt::String>>,
  pub provisioning_state: Option<_rt::String>,
  pub circuit: Option<_rt::String>,
  pub endpoints: Option<_rt::String>,
  pub network_block: _rt::String,
  pub management_network: Option<_rt::String>,
  pub provisioning_network: Option<_rt::String>,
  pub vmotion_network: Option<_rt::String>,
  pub vcenter_password: Option<_rt::String>,
  pub nsxt_password: Option<_rt::String>,
  pub vcenter_certificate_thumbprint: Option<_rt::String>,
  pub nsxt_certificate_thumbprint: Option<_rt::String>,
  pub external_cloud_links: Option<_rt::Vec::<_rt::String>>,
  pub secondary_circuit: Option<_rt::String>,
  pub nsx_public_ip_quota_raised: Option<_rt::String>,
  pub virtual_network_id: Option<_rt::String>,
  pub dns_zone_type: Option<_rt::String>,
}
impl ::core::fmt::Debug for PrivateCloud {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    f.debug_struct("PrivateCloud").field("management-cluster", &self.management_cluster).field("internet", &self.internet).field("identity-sources", &self.identity_sources).field("availability", &self.availability).field("encryption", &self.encryption).field("extended-network-blocks", &self.extended_network_blocks).field("provisioning-state", &self.provisioning_state).field("circuit", &self.circuit).field("endpoints", &self.endpoints).field("network-block", &self.network_block).field("management-network", &self.management_network).field("provisioning-network", &self.provisioning_network).field("vmotion-network", &self.vmotion_network).field("vcenter-password", &self.vcenter_password).field("nsxt-password", &self.nsxt_password).field("vcenter-certificate-thumbprint", &self.vcenter_certificate_thumbprint).field("nsxt-certificate-thumbprint", &self.nsxt_certificate_thumbprint).field("external-cloud-links", &self.external_cloud_links).field("secondary-circuit", &self.secondary_circuit).field("nsx-public-ip-quota-raised", &self.nsx_public_ip_quota_raised).field("virtual-network-id", &self.virtual_network_id).field("dns-zone-type", &self.dns_zone_type).finish()
  }
}
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_list_private_clouds_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result1 = {
  let len0 = arg1;
  let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
  T::list_private_clouds(_rt::string_lift(bytes0))
};
let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
match result1 {
  Ok(e) => { {
    *ptr2.add(0).cast::<u8>() = (0i32) as u8;
    let vec29 = e;
    let len29 = vec29.len();
    let layout29 = _rt::alloc::Layout::from_size_align(vec29.len() * (64*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
  let (result29, _cleanup29) = wit_bindgen_rt::Cleanup::new(layout29);if let Some(cleanup) = _cleanup29 { cleanup.forget(); }
    for (i, e) in vec29.into_iter().enumerate() {
      let base = result29.add(i * (64*::core::mem::size_of::<*const u8>()));
      {
        let PrivateCloud{ management_cluster:management_cluster3, internet:internet3, identity_sources:identity_sources3, availability:availability3, encryption:encryption3, extended_network_blocks:extended_network_blocks3, provisioning_state:provisioning_state3, circuit:circuit3, endpoints:endpoints3, network_block:network_block3, management_network:management_network3, provisioning_network:provisioning_network3, vmotion_network:vmotion_network3, vcenter_password:vcenter_password3, nsxt_password:nsxt_password3, vcenter_certificate_thumbprint:vcenter_certificate_thumbprint3, nsxt_certificate_thumbprint:nsxt_certificate_thumbprint3, external_cloud_links:external_cloud_links3, secondary_circuit:secondary_circuit3, nsx_public_ip_quota_raised:nsx_public_ip_quota_raised3, virtual_network_id:virtual_network_id3, dns_zone_type:dns_zone_type3, } = e;
        let vec4 = (management_cluster3.into_bytes()).into_boxed_slice();
        let ptr4 = vec4.as_ptr().cast::<u8>();
        let len4 = vec4.len();
        ::core::mem::forget(vec4);
        *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
        *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
        match internet3 {
          Some(e) => {
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
          },
          None => {
            {
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match identity_sources3 {
          Some(e) => {
            *base.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec7 = e;
            let len7 = vec7.len();
            let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result7, _cleanup7) = wit_bindgen_rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
            for (i, e) in vec7.into_iter().enumerate() {
              let base = result7.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let vec6 = (e.into_bytes()).into_boxed_slice();
                let ptr6 = vec6.as_ptr().cast::<u8>();
                let len6 = vec6.len();
                ::core::mem::forget(vec6);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
              }
            }
            *base.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
            *base.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result7;
          },
          None => {
            {
              *base.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match availability3 {
          Some(e) => {
            *base.add(8*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec8 = (e.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *base.add(10*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *base.add(9*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
          },
          None => {
            {
              *base.add(8*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match encryption3 {
          Some(e) => {
            *base.add(11*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec9 = (e.into_bytes()).into_boxed_slice();
            let ptr9 = vec9.as_ptr().cast::<u8>();
            let len9 = vec9.len();
            ::core::mem::forget(vec9);
            *base.add(13*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
            *base.add(12*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
          },
          None => {
            {
              *base.add(11*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match extended_network_blocks3 {
          Some(e) => {
            *base.add(14*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec11 = e;
            let len11 = vec11.len();
            let layout11 = _rt::alloc::Layout::from_size_align(vec11.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result11, _cleanup11) = wit_bindgen_rt::Cleanup::new(layout11);if let Some(cleanup) = _cleanup11 { cleanup.forget(); }
            for (i, e) in vec11.into_iter().enumerate() {
              let base = result11.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let vec10 = (e.into_bytes()).into_boxed_slice();
                let ptr10 = vec10.as_ptr().cast::<u8>();
                let len10 = vec10.len();
                ::core::mem::forget(vec10);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
                *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
              }
            }
            *base.add(16*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
            *base.add(15*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result11;
          },
          None => {
            {
              *base.add(14*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match provisioning_state3 {
          Some(e) => {
            *base.add(17*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec12 = (e.into_bytes()).into_boxed_slice();
            let ptr12 = vec12.as_ptr().cast::<u8>();
            let len12 = vec12.len();
            ::core::mem::forget(vec12);
            *base.add(19*::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
            *base.add(18*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr12.cast_mut();
          },
          None => {
            {
              *base.add(17*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match circuit3 {
          Some(e) => {
            *base.add(20*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec13 = (e.into_bytes()).into_boxed_slice();
            let ptr13 = vec13.as_ptr().cast::<u8>();
            let len13 = vec13.len();
            ::core::mem::forget(vec13);
            *base.add(22*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
            *base.add(21*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
          },
          None => {
            {
              *base.add(20*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match endpoints3 {
          Some(e) => {
            *base.add(23*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec14 = (e.into_bytes()).into_boxed_slice();
            let ptr14 = vec14.as_ptr().cast::<u8>();
            let len14 = vec14.len();
            ::core::mem::forget(vec14);
            *base.add(25*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
            *base.add(24*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr14.cast_mut();
          },
          None => {
            {
              *base.add(23*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };let vec15 = (network_block3.into_bytes()).into_boxed_slice();
        let ptr15 = vec15.as_ptr().cast::<u8>();
        let len15 = vec15.len();
        ::core::mem::forget(vec15);
        *base.add(27*::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
        *base.add(26*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15.cast_mut();
        match management_network3 {
          Some(e) => {
            *base.add(28*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec16 = (e.into_bytes()).into_boxed_slice();
            let ptr16 = vec16.as_ptr().cast::<u8>();
            let len16 = vec16.len();
            ::core::mem::forget(vec16);
            *base.add(30*::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
            *base.add(29*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr16.cast_mut();
          },
          None => {
            {
              *base.add(28*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match provisioning_network3 {
          Some(e) => {
            *base.add(31*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec17 = (e.into_bytes()).into_boxed_slice();
            let ptr17 = vec17.as_ptr().cast::<u8>();
            let len17 = vec17.len();
            ::core::mem::forget(vec17);
            *base.add(33*::core::mem::size_of::<*const u8>()).cast::<usize>() = len17;
            *base.add(32*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr17.cast_mut();
          },
          None => {
            {
              *base.add(31*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match vmotion_network3 {
          Some(e) => {
            *base.add(34*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec18 = (e.into_bytes()).into_boxed_slice();
            let ptr18 = vec18.as_ptr().cast::<u8>();
            let len18 = vec18.len();
            ::core::mem::forget(vec18);
            *base.add(36*::core::mem::size_of::<*const u8>()).cast::<usize>() = len18;
            *base.add(35*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr18.cast_mut();
          },
          None => {
            {
              *base.add(34*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match vcenter_password3 {
          Some(e) => {
            *base.add(37*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec19 = (e.into_bytes()).into_boxed_slice();
            let ptr19 = vec19.as_ptr().cast::<u8>();
            let len19 = vec19.len();
            ::core::mem::forget(vec19);
            *base.add(39*::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
            *base.add(38*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr19.cast_mut();
          },
          None => {
            {
              *base.add(37*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match nsxt_password3 {
          Some(e) => {
            *base.add(40*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec20 = (e.into_bytes()).into_boxed_slice();
            let ptr20 = vec20.as_ptr().cast::<u8>();
            let len20 = vec20.len();
            ::core::mem::forget(vec20);
            *base.add(42*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
            *base.add(41*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr20.cast_mut();
          },
          None => {
            {
              *base.add(40*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match vcenter_certificate_thumbprint3 {
          Some(e) => {
            *base.add(43*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec21 = (e.into_bytes()).into_boxed_slice();
            let ptr21 = vec21.as_ptr().cast::<u8>();
            let len21 = vec21.len();
            ::core::mem::forget(vec21);
            *base.add(45*::core::mem::size_of::<*const u8>()).cast::<usize>() = len21;
            *base.add(44*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr21.cast_mut();
          },
          None => {
            {
              *base.add(43*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match nsxt_certificate_thumbprint3 {
          Some(e) => {
            *base.add(46*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec22 = (e.into_bytes()).into_boxed_slice();
            let ptr22 = vec22.as_ptr().cast::<u8>();
            let len22 = vec22.len();
            ::core::mem::forget(vec22);
            *base.add(48*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
            *base.add(47*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr22.cast_mut();
          },
          None => {
            {
              *base.add(46*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match external_cloud_links3 {
          Some(e) => {
            *base.add(49*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec24 = e;
            let len24 = vec24.len();
            let layout24 = _rt::alloc::Layout::from_size_align(vec24.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result24, _cleanup24) = wit_bindgen_rt::Cleanup::new(layout24);if let Some(cleanup) = _cleanup24 { cleanup.forget(); }
            for (i, e) in vec24.into_iter().enumerate() {
              let base = result24.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let vec23 = (e.into_bytes()).into_boxed_slice();
                let ptr23 = vec23.as_ptr().cast::<u8>();
                let len23 = vec23.len();
                ::core::mem::forget(vec23);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
                *base.add(0).cast::<*mut u8>() = ptr23.cast_mut();
              }
            }
            *base.add(51*::core::mem::size_of::<*const u8>()).cast::<usize>() = len24;
            *base.add(50*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result24;
          },
          None => {
            {
              *base.add(49*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match secondary_circuit3 {
          Some(e) => {
            *base.add(52*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec25 = (e.into_bytes()).into_boxed_slice();
            let ptr25 = vec25.as_ptr().cast::<u8>();
            let len25 = vec25.len();
            ::core::mem::forget(vec25);
            *base.add(54*::core::mem::size_of::<*const u8>()).cast::<usize>() = len25;
            *base.add(53*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr25.cast_mut();
          },
          None => {
            {
              *base.add(52*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match nsx_public_ip_quota_raised3 {
          Some(e) => {
            *base.add(55*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec26 = (e.into_bytes()).into_boxed_slice();
            let ptr26 = vec26.as_ptr().cast::<u8>();
            let len26 = vec26.len();
            ::core::mem::forget(vec26);
            *base.add(57*::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
            *base.add(56*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr26.cast_mut();
          },
          None => {
            {
              *base.add(55*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match virtual_network_id3 {
          Some(e) => {
            *base.add(58*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec27 = (e.into_bytes()).into_boxed_slice();
            let ptr27 = vec27.as_ptr().cast::<u8>();
            let len27 = vec27.len();
            ::core::mem::forget(vec27);
            *base.add(60*::core::mem::size_of::<*const u8>()).cast::<usize>() = len27;
            *base.add(59*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr27.cast_mut();
          },
          None => {
            {
              *base.add(58*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match dns_zone_type3 {
          Some(e) => {
            *base.add(61*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec28 = (e.into_bytes()).into_boxed_slice();
            let ptr28 = vec28.as_ptr().cast::<u8>();
            let len28 = vec28.len();
            ::core::mem::forget(vec28);
            *base.add(63*::core::mem::size_of::<*const u8>()).cast::<usize>() = len28;
            *base.add(62*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr28.cast_mut();
          },
          None => {
            {
              *base.add(61*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };}
      }
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len29;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result29;
    } },
    Err(e) => { {
      *ptr2.add(0).cast::<u8>() = (1i32) as u8;
      let vec30 = (e.into_bytes()).into_boxed_slice();
      let ptr30 = vec30.as_ptr().cast::<u8>();
      let len30 = vec30.len();
      ::core::mem::forget(vec30);
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len30;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr30.cast_mut();
    } },
  };ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_list_private_clouds<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base76 = l1;
      let len76 = l2;
      for i in 0..len76 {
        let base = base76.add(i * (64*::core::mem::size_of::<*const u8>()));
        {
          let l3 = *base.add(0).cast::<*mut u8>();
          let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = i32::from(*base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l5 {
            0 => (),
            _ => {
              let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l7 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l6, l7, 1);
            },
          }
          let l8 = i32::from(*base.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l8 {
            0 => (),
            _ => {
              let l9 = *base.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l10 = *base.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let base13 = l9;
              let len13 = l10;
              for i in 0..len13 {
                let base = base13.add(i * (2*::core::mem::size_of::<*const u8>()));
                {
                  let l11 = *base.add(0).cast::<*mut u8>();
                  let l12 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l11, l12, 1);
                }
              }
              _rt::cabi_dealloc(base13, len13 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            },
          }
          let l14 = i32::from(*base.add(8*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l14 {
            0 => (),
            _ => {
              let l15 = *base.add(9*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l16 = *base.add(10*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l15, l16, 1);
            },
          }
          let l17 = i32::from(*base.add(11*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l17 {
            0 => (),
            _ => {
              let l18 = *base.add(12*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l19 = *base.add(13*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l18, l19, 1);
            },
          }
          let l20 = i32::from(*base.add(14*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l20 {
            0 => (),
            _ => {
              let l21 = *base.add(15*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l22 = *base.add(16*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let base25 = l21;
              let len25 = l22;
              for i in 0..len25 {
                let base = base25.add(i * (2*::core::mem::size_of::<*const u8>()));
                {
                  let l23 = *base.add(0).cast::<*mut u8>();
                  let l24 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l23, l24, 1);
                }
              }
              _rt::cabi_dealloc(base25, len25 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            },
          }
          let l26 = i32::from(*base.add(17*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l26 {
            0 => (),
            _ => {
              let l27 = *base.add(18*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l28 = *base.add(19*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l27, l28, 1);
            },
          }
          let l29 = i32::from(*base.add(20*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l29 {
            0 => (),
            _ => {
              let l30 = *base.add(21*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l31 = *base.add(22*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l30, l31, 1);
            },
          }
          let l32 = i32::from(*base.add(23*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l32 {
            0 => (),
            _ => {
              let l33 = *base.add(24*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l34 = *base.add(25*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l33, l34, 1);
            },
          }
          let l35 = *base.add(26*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l36 = *base.add(27*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l35, l36, 1);
          let l37 = i32::from(*base.add(28*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l37 {
            0 => (),
            _ => {
              let l38 = *base.add(29*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l39 = *base.add(30*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l38, l39, 1);
            },
          }
          let l40 = i32::from(*base.add(31*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l40 {
            0 => (),
            _ => {
              let l41 = *base.add(32*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l42 = *base.add(33*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l41, l42, 1);
            },
          }
          let l43 = i32::from(*base.add(34*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l43 {
            0 => (),
            _ => {
              let l44 = *base.add(35*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l45 = *base.add(36*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l44, l45, 1);
            },
          }
          let l46 = i32::from(*base.add(37*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l46 {
            0 => (),
            _ => {
              let l47 = *base.add(38*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l48 = *base.add(39*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l47, l48, 1);
            },
          }
          let l49 = i32::from(*base.add(40*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l49 {
            0 => (),
            _ => {
              let l50 = *base.add(41*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l51 = *base.add(42*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l50, l51, 1);
            },
          }
          let l52 = i32::from(*base.add(43*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l52 {
            0 => (),
            _ => {
              let l53 = *base.add(44*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l54 = *base.add(45*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l53, l54, 1);
            },
          }
          let l55 = i32::from(*base.add(46*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l55 {
            0 => (),
            _ => {
              let l56 = *base.add(47*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l57 = *base.add(48*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l56, l57, 1);
            },
          }
          let l58 = i32::from(*base.add(49*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l58 {
            0 => (),
            _ => {
              let l59 = *base.add(50*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l60 = *base.add(51*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let base63 = l59;
              let len63 = l60;
              for i in 0..len63 {
                let base = base63.add(i * (2*::core::mem::size_of::<*const u8>()));
                {
                  let l61 = *base.add(0).cast::<*mut u8>();
                  let l62 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l61, l62, 1);
                }
              }
              _rt::cabi_dealloc(base63, len63 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            },
          }
          let l64 = i32::from(*base.add(52*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l64 {
            0 => (),
            _ => {
              let l65 = *base.add(53*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l66 = *base.add(54*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l65, l66, 1);
            },
          }
          let l67 = i32::from(*base.add(55*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l67 {
            0 => (),
            _ => {
              let l68 = *base.add(56*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l69 = *base.add(57*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l68, l69, 1);
            },
          }
          let l70 = i32::from(*base.add(58*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l70 {
            0 => (),
            _ => {
              let l71 = *base.add(59*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l72 = *base.add(60*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l71, l72, 1);
            },
          }
          let l73 = i32::from(*base.add(61*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l73 {
            0 => (),
            _ => {
              let l74 = *base.add(62*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l75 = *base.add(63*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l74, l75, 1);
            },
          }
        }
      }
      _rt::cabi_dealloc(base76, len76 * (64*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    },
    _ => {
      let l77 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l78 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l77, l78, 1);
    },
  }
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn list_private_clouds(subscription_id: _rt::String,) -> Result<_rt::Vec::<PrivateCloud>,_rt::String>;
}
#[doc(hidden)]

macro_rules! __export_world_avs_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "list-private-clouds")]
    unsafe extern "C" fn export_list_private_clouds(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_list_private_clouds_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_list-private-clouds")]
    unsafe extern "C" fn _post_return_list_private_clouds(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_list_private_clouds::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_avs_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
  wit_bindgen_rt::run_ctors_once();
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub use alloc_crate::alloc;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_avs_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_avs_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_avs_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.45.1:component:avs-rs:avs:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 650] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x90\x04\x01A\x02\x01\
A\x09\x01ks\x01ps\x01k\x01\x01r\x16\x12management-clusters\x08internet\0\x10iden\
tity-sources\x02\x0cavailability\0\x0aencryption\0\x17extended-network-blocks\x02\
\x12provisioning-state\0\x07circuit\0\x09endpoints\0\x0dnetwork-blocks\x12manage\
ment-network\0\x14provisioning-network\0\x0fvmotion-network\0\x10vcenter-passwor\
d\0\x0dnsxt-password\0\x1evcenter-certificate-thumbprint\0\x1bnsxt-certificate-t\
humbprint\0\x14external-cloud-links\x02\x11secondary-circuit\0\x1ansx-public-ip-\
quota-raised\0\x12virtual-network-id\0\x0ddns-zone-type\0\x03\0\x0dprivate-cloud\
\x03\0\x03\x01p\x04\x01j\x01\x05\x01s\x01@\x01\x0fsubscription-ids\0\x06\x04\0\x13\
list-private-clouds\x01\x07\x04\0\x14component:avs-rs/avs\x04\0\x0b\x09\x01\0\x03\
avs\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.238.1\x10\
wit-bindgen-rust\x060.45.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen_rt::maybe_link_cabi_realloc();
}

